"""Typed, perception-only screen analysis."""

from work_agent.vision.analyzer import ScreenAnalyzer
from work_agent.vision.config import VisionSettings
from work_agent.vision.coordinates import (
    PixelBoundingBox,
    PixelPoint,
    bounding_box_to_pixels,
    normalized_to_pixel,
)
from work_agent.vision.errors import (
    VisionAuthenticationError,
    VisionConfigurationError,
    VisionCoordinateError,
    VisionError,
    VisionImageError,
    VisionNetworkError,
    VisionPermissionError,
    VisionRateLimitError,
    VisionRequestError,
    VisionServerError,
    VisionStructuredOutputError,
    VisionTimeoutError,
)
from work_agent.vision.images import DecodedImage, decode_image, load_image
from work_agent.vision.models import (
    ActionVerification,
    AnalysisOptions,
    AnalysisUsage,
    BoundingBox,
    ImageDetail,
    NormalizedPoint,
    ObservationContext,
    ReasoningEffort,
    SafetyWarning,
    ScreenAnalysis,
    ScreenObservation,
    ScreenObservationPerception,
    ScreenPerception,
    ScreenState,
    ServiceTier,
    UIElement,
    UIElementRole,
    VerificationStatus,
)
from work_agent.vision.openai_analyzer import OpenAIScreenAnalyzer
from work_agent.vision.overlay import save_analysis_overlay

__all__ = [
    "ActionVerification",
    "AnalysisOptions",
    "AnalysisUsage",
    "BoundingBox",
    "DecodedImage",
    "ImageDetail",
    "NormalizedPoint",
    "ObservationContext",
    "OpenAIScreenAnalyzer",
    "PixelBoundingBox",
    "PixelPoint",
    "ReasoningEffort",
    "SafetyWarning",
    "ScreenAnalysis",
    "ScreenAnalyzer",
    "ScreenObservation",
    "ScreenObservationPerception",
    "ScreenPerception",
    "ScreenState",
    "ServiceTier",
    "UIElement",
    "UIElementRole",
    "VerificationStatus",
    "VisionAuthenticationError",
    "VisionConfigurationError",
    "VisionCoordinateError",
    "VisionError",
    "VisionImageError",
    "VisionNetworkError",
    "VisionPermissionError",
    "VisionRateLimitError",
    "VisionRequestError",
    "VisionServerError",
    "VisionSettings",
    "VisionStructuredOutputError",
    "VisionTimeoutError",
    "bounding_box_to_pixels",
    "decode_image",
    "load_image",
    "normalized_to_pixel",
    "save_analysis_overlay",
]
